find src/ -name "*.tsx" -type f -exec sed -i -e 's/text-white/text-zinc-900/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/text-zinc-300/text-zinc-700/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/text-zinc-400/text-zinc-500/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-white\/5/bg-zinc-50/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-white\/10/bg-zinc-100/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-white\/15/bg-zinc-200/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-white\/20/bg-zinc-200/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/border-white\/5/border-zinc-100/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/border-white\/10/border-zinc-200/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/border-white\/20/border-zinc-300/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-\[#0a0a0a\]/bg-white/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/text-violet-400/text-indigo-600/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/text-violet-300/text-indigo-500/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/text-violet-500/text-indigo-600/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-violet-600/bg-indigo-600/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-violet-500/bg-indigo-500/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/hover:bg-violet-700/hover:bg-indigo-700/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/hover:bg-violet-600/hover:bg-indigo-600/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-violet-500\/10/bg-indigo-50/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/border-violet-500\/20/border-indigo-200/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/border-violet-500\/30/border-indigo-300/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-zinc-800/bg-zinc-100/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/bg-zinc-900/bg-white/g' {} +
find src/ -name "*.tsx" -type f -exec sed -i -e 's/text-zinc-500\/70/text-zinc-400/g' {} +
