import React, { useRef, useState } from "react";
import { FileLock2, Upload, X, ShieldCheck, AlertTriangle } from "lucide-react";
import { OfflineBallot } from "../types";

interface OfflineBallotImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  token: string;
  onImported: () => Promise<void>;
  setErrorNotification: (message: string) => void;
  setSuccessNotification: (message: string) => void;
}

export default function OfflineBallotImportModal({
  isOpen,
  onClose,
  token,
  onImported,
  setErrorNotification,
  setSuccessNotification,
}: OfflineBallotImportModalProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [filename, setFilename] = useState("");
  const [ballot, setBallot] = useState<OfflineBallot | null>(null);
  const [importing, setImporting] = useState(false);

  if (!isOpen) return null;

  const selectFile = async (file?: File) => {
    setBallot(null);
    setFilename(file?.name || "");
    if (!file) return;
    if (file.size > 1024 * 1024) {
      setErrorNotification("Offline ballot files must be smaller than 1 MB.");
      return;
    }
    try {
      const parsed = JSON.parse(await file.text());
      if (
        parsed?.version !== 1 ||
        parsed?.algorithm !== "ECDH-P256/HKDF-SHA256/AES-256-GCM" ||
        !parsed?.ephemeralPublicKey ||
        !parsed?.salt ||
        !parsed?.iv ||
        !parsed?.ciphertext
      ) throw new Error("This is not a supported encrypted offline ballot file");
      setBallot(parsed);
    } catch (error: any) {
      setErrorNotification(error.message || "Could not read the offline ballot JSON file");
    }
  };

  const importBallot = async () => {
    if (!ballot) return;
    setImporting(true);
    try {
      const response = await fetch("/api/votes/import-offline", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ ballot }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Offline ballot import failed");
      setSuccessNotification(data.message || `Imported offline ballot for ${data.studentName}.`);
      await onImported();
      setBallot(null);
      setFilename("");
      onClose();
    } catch (error: any) {
      setErrorNotification(error.message || "Offline ballot import failed");
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="w-full max-w-lg bg-white rounded-2xl border border-slate-200 shadow-2xl overflow-hidden">
        <div className="p-5 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-sky-50 text-sky-700 rounded-xl flex items-center justify-center border border-sky-200">
              <FileLock2 size={20} />
            </div>
            <div>
              <h3 className="font-display font-extrabold text-slate-900 text-sm">Import Offline Ballot</h3>
              <p className="text-xs text-slate-500">Decrypt, authenticate, validate, and record a student's ballot.</p>
            </div>
          </div>
          <button type="button" onClick={onClose} className="p-2 text-slate-400 hover:text-slate-700 cursor-pointer"><X size={18} /></button>
        </div>

        <div className="p-5 space-y-4">
          <input
            ref={inputRef}
            type="file"
            accept="application/json,.json"
            className="hidden"
            onChange={(event) => selectFile(event.target.files?.[0])}
          />
          <button
            type="button"
            onClick={() => inputRef.current?.click()}
            className="w-full border-2 border-dashed border-slate-300 hover:border-sky-400 bg-slate-50 hover:bg-sky-50 rounded-2xl p-8 flex flex-col items-center gap-2 cursor-pointer transition-all"
          >
            <Upload size={24} className="text-sky-600" />
            <span className="text-xs font-bold text-slate-800">Choose encrypted JSON ballot</span>
            <span className="text-[11px] text-slate-500">{filename || "Only files generated by the student offline voting screen are accepted."}</span>
          </button>

          {ballot ? (
            <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl flex gap-2 text-xs text-emerald-800">
              <ShieldCheck size={17} className="shrink-0" />
              <span>Encrypted envelope format recognized. The backend will verify its signed permit, identity, election eligibility, timestamp, nonce, and every selection.</span>
            </div>
          ) : (
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl flex gap-2 text-xs text-amber-800">
              <AlertTriangle size={17} className="shrink-0" />
              <span>Do not edit or convert the file. Any changed ciphertext is rejected as tampered.</span>
            </div>
          )}
        </div>

        <div className="p-5 border-t border-slate-200 bg-slate-50 flex justify-end gap-3">
          <button type="button" onClick={onClose} className="px-4 py-2 text-xs font-bold text-slate-600 cursor-pointer">Cancel</button>
          <button
            type="button"
            onClick={importBallot}
            disabled={!ballot || importing}
            className="px-5 py-2.5 bg-sky-600 hover:bg-sky-500 disabled:bg-slate-300 text-white rounded-xl text-xs font-bold cursor-pointer disabled:cursor-not-allowed"
          >
            {importing ? "Verifying & Importing..." : "Verify & Import Ballot"}
          </button>
        </div>
      </div>
    </div>
  );
}
